title: Khulnasoft Open Source
email:
description: Khulnasoft Open Source

twitter_username: openatkhulnasoft
github_username: khulnasoft

cdn: https://opensource.devopsedge.net

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-octicons

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.

collections:
  projects:
    output: false
  posts:
    output: false
  community:
    output: false
  fossfund:
    output: false

exclude:
  - README.md
  - Brewfile
  - Brewfile.lock.json
  - CODE_OF_CONDUCT.md
  - content.json
  - CONTRIBUTING.md
  - LICENSE
  - localbuilder.sh
  - Gemfile
  - SECURITY.md
  - Gemfile.lock
  - CNAME
  - Dockerfile
  - Dockerfile.builder
  - script
  - vendor/gems
  - node_modules
  - node_modules/**/CHANGELOG.md
  - CHANGELOG.md
  - gulpfile.js
  - package.json
  - package-lock.json
seo:

twitter:
  username: openatkhulnasoft

defaults:
  -
    scope:
      path: ""
    values:
      image: https://opensource.devopsedge.net/assets/images/social-card.png
      layout: default
